server:
  port: 3000
  servlet:
    context-path: /payment
spring:
  application:
    name: PAYMENT-SERVICE
  #####Database Config#####
  datasource:
    url: jdbc:h2:file:./database/payment_db
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enable: true
  boot:
    admin:
      client:
        url: http://host.docker.internal:8888
  #####Database Config####
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    prefer-ip-address: true